# Generated by Django 6.0.2 on 2026-02-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_date_of_birth_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('N', 'Prefer not to say'), ('M', 'Male'), ('F', 'Female')], default='N'),
        ),
    ]
