# Generated by Django 6.0.2 on 2026-03-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_usermovielist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='rating',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='usermovielist',
            name='tmdb_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
